input_dict:
  northern_flow: Flow (cfs)
  exports: Flow (cfs)
  sjr_flow: Flow (cfs)
  sjr_vernalis_ec: EC (uS/cm)
  sac_greens_ec: EC (uS/cm)

water_yrs: #toDo
  - 2014

output_vars:
    - RSMKL008
    - RSAN032
    - RSAN037
    - RSAC092
    - SLTRM004
    - ROLD024
    - CHVCT000
    - RSAN018
    - CHSWP003
    - CHDMC006
    - SLDUT007
    - RSAN072
    - OLD_MID
    - RSAN058
    - ROLD059
    - RSAN007
    - RSAC081
    - SLMZU025
    - RSAC075
    - SLMZU011
    - SLSUS012
    - SLCBN002
    - RSAC064

name_mapping:
  RSAC092: EMMATON
  CHDMC006: CVP INTAKE
  CHSWP003: CCFB_INTAKE
  CHVCT000: VICTORIA INTAKE
  OLD_MID: OLD RIVER NEAR MIDDLE RIVER
  ROLD024: OLD RIVER AT BACON ISLAND
  ROLD059: OLD RIVER AT TRACY BLVD
  RSAC064: SACRAMENTO R AT PORT CHICAGO
  RSAC075: MALLARDISLAND
  RSAC081: COLLINSVILLE
  RSAN007: ANTIOCH
  RSAN018: JERSEYPOINT
  RSAN032: SACRAMENTO R AT SAN ANDREAS LANDING
  RSAN037: SAN JOAQUIN R AT PRISONERS POINT
  RSAN058: ROUGH AND READY ISLAND
  RSAN072: SAN JOAQUIN R AT BRANDT BRIDGE
  RSMKL008: S FORK MOKELUMNE AT TERMINOUS
  SLCBN002: CHADBOURNE SLOUGH NR SUNRISE DUCK CLUB
  SLDUT007: DUTCH SLOUGH
  SLMZU011: MONTEZUMA SL AT BELDONS LANDING
  SLMZU025: MONTEZUMA SL AT NATIONAL STEEL
  SLSUS012: SUISUN SL NEAR VOLANTI SL
  SLTRM004: THREE MILE SLOUGH NR SAN JOAQUIN R