name: ann
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - matplotlib
  - pandas
  - holoviews
  - hvplot
  - panel
  - pillow == 9.0.1
  - dask
  - diskcache
  # data
  - aiohttp
  - requests
  - pip:
    - scikit-learn
    - tensorflow